apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: gpu-platform-control-plane
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: kustomize
  name: gateway
  namespace: system
