apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: gpu-platform-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: gpu-platform-control-plane
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: gpu-platform-control-plane
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: gpu-platform-control-plane
    spec:
      # 아래 코드를 주석 해제하면 solution이 지원하는 platform에 맞게,
      # nodeAffinity 식을 설정할 수 있다,
      # 여러 architecture를 지원하는 것이 권장되며,
      # manager image는 makefile의 docker-buildx target으로 빌드할 수 있다.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      # - matchExpressions:
      # - key: kubernetes.io/arch
      # operator: In
      #             values:
      # - amd64
      # - arm64
      # - ppc64le
      # - s390x
      # - key: kubernetes.io/os
      # operator: In
      #             values:
      # - linux
      securityContext:
        # 이 project는 기본적으로 "restricted" Pod Security Standards를 따르도록 설정되어 있다,
        # 이를 통해 deployment가 Kubernetes의 가장 높은 보안 요건을 충족한다,
        # 자세한 내용은 https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted 참고.
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: controller:latest
        name: manager
        ports:
        - containerPort: 8081
          name: health
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # project 요구사항에 맞게 resource를 적절히 설정한다,
        # 자세한 내용은 https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ 참고.
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
