//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *FaultSignal) DeepCopyInto(out *FaultSignal) {
	*out = *in
}

// 리시버를 복사해 새 FaultSignal 생성, 자동 생성 deepcopy 함수
func (in *FaultSignal) DeepCopy() *FaultSignal {
	if in == nil {
		return nil
	}
	out := new(FaultSignal)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *GPUQuotaLimits) DeepCopyInto(out *GPUQuotaLimits) {
	*out = *in
}

// 리시버를 복사해 새 GPUQuotaLimits 생성, 자동 생성 deepcopy 함수
func (in *GPUQuotaLimits) DeepCopy() *GPUQuotaLimits {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaLimits)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *GPUQuotaPolicy) DeepCopyInto(out *GPUQuotaPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// 리시버를 복사해 새 GPUQuotaPolicy 생성, 자동 생성 deepcopy 함수
func (in *GPUQuotaPolicy) DeepCopy() *GPUQuotaPolicy {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaPolicy)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *GPUQuotaPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *GPUQuotaPolicyList) DeepCopyInto(out *GPUQuotaPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUQuotaPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 GPUQuotaPolicyList 생성, 자동 생성 deepcopy 함수
func (in *GPUQuotaPolicyList) DeepCopy() *GPUQuotaPolicyList {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaPolicyList)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *GPUQuotaPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *GPUQuotaPolicySpec) DeepCopyInto(out *GPUQuotaPolicySpec) {
	*out = *in
	out.Limits = in.Limits
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(GPUQuotaRateLimit)
		**out = **in
	}
}

// 리시버를 복사해 새 GPUQuotaPolicySpec 생성, 자동 생성 deepcopy 함수
func (in *GPUQuotaPolicySpec) DeepCopy() *GPUQuotaPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *GPUQuotaPolicyStatus) DeepCopyInto(out *GPUQuotaPolicyStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 GPUQuotaPolicyStatus 생성, 자동 생성 deepcopy 함수
func (in *GPUQuotaPolicyStatus) DeepCopy() *GPUQuotaPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *GPUQuotaRateLimit) DeepCopyInto(out *GPUQuotaRateLimit) {
	*out = *in
}

// 리시버를 복사해 새 GPUQuotaRateLimit 생성, 자동 생성 deepcopy 함수
func (in *GPUQuotaRateLimit) DeepCopy() *GPUQuotaRateLimit {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaRateLimit)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *InferenceDeployment) DeepCopyInto(out *InferenceDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// 리시버를 복사해 새 InferenceDeployment 생성, 자동 생성 deepcopy 함수
func (in *InferenceDeployment) DeepCopy() *InferenceDeployment {
	if in == nil {
		return nil
	}
	out := new(InferenceDeployment)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *InferenceDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *InferenceDeploymentList) DeepCopyInto(out *InferenceDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferenceDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 InferenceDeploymentList 생성, 자동 생성 deepcopy 함수
func (in *InferenceDeploymentList) DeepCopy() *InferenceDeploymentList {
	if in == nil {
		return nil
	}
	out := new(InferenceDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *InferenceDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *InferenceDeploymentSpec) DeepCopyInto(out *InferenceDeploymentSpec) {
	*out = *in
	out.Model = in.Model
}

// 리시버를 복사해 새 InferenceDeploymentSpec 생성, 자동 생성 deepcopy 함수
func (in *InferenceDeploymentSpec) DeepCopy() *InferenceDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *InferenceDeploymentStatus) DeepCopyInto(out *InferenceDeploymentStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 InferenceDeploymentStatus 생성, 자동 생성 deepcopy 함수
func (in *InferenceDeploymentStatus) DeepCopy() *InferenceDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *InferenceModel) DeepCopyInto(out *InferenceModel) {
	*out = *in
}

// 리시버를 복사해 새 InferenceModel 생성, 자동 생성 deepcopy 함수
func (in *InferenceModel) DeepCopy() *InferenceModel {
	if in == nil {
		return nil
	}
	out := new(InferenceModel)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *MLTrainingJob) DeepCopyInto(out *MLTrainingJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// 리시버를 복사해 새 MLTrainingJob 생성, 자동 생성 deepcopy 함수
func (in *MLTrainingJob) DeepCopy() *MLTrainingJob {
	if in == nil {
		return nil
	}
	out := new(MLTrainingJob)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *MLTrainingJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *MLTrainingJobList) DeepCopyInto(out *MLTrainingJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MLTrainingJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 MLTrainingJobList 생성, 자동 생성 deepcopy 함수
func (in *MLTrainingJobList) DeepCopy() *MLTrainingJobList {
	if in == nil {
		return nil
	}
	out := new(MLTrainingJobList)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *MLTrainingJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *MLTrainingJobSpec) DeepCopyInto(out *MLTrainingJobSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// 리시버를 복사해 새 MLTrainingJobSpec 생성, 자동 생성 deepcopy 함수
func (in *MLTrainingJobSpec) DeepCopy() *MLTrainingJobSpec {
	if in == nil {
		return nil
	}
	out := new(MLTrainingJobSpec)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *MLTrainingJobStatus) DeepCopyInto(out *MLTrainingJobStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
	if in.RunningObservedAt != nil {
		in, out := &in.RunningObservedAt, &out.RunningObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 MLTrainingJobStatus 생성, 자동 생성 deepcopy 함수
func (in *MLTrainingJobStatus) DeepCopy() *MLTrainingJobStatus {
	if in == nil {
		return nil
	}
	out := new(MLTrainingJobStatus)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *NodeHealth) DeepCopyInto(out *NodeHealth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// 리시버를 복사해 새 NodeHealth 생성, 자동 생성 deepcopy 함수
func (in *NodeHealth) DeepCopy() *NodeHealth {
	if in == nil {
		return nil
	}
	out := new(NodeHealth)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *NodeHealth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *NodeHealthList) DeepCopyInto(out *NodeHealthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeHealth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 NodeHealthList 생성, 자동 생성 deepcopy 함수
func (in *NodeHealthList) DeepCopy() *NodeHealthList {
	if in == nil {
		return nil
	}
	out := new(NodeHealthList)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *NodeHealthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *NodeHealthSpec) DeepCopyInto(out *NodeHealthSpec) {
	*out = *in
}

// 리시버를 복사해 새 NodeHealthSpec 생성, 자동 생성 deepcopy 함수
func (in *NodeHealthSpec) DeepCopy() *NodeHealthSpec {
	if in == nil {
		return nil
	}
	out := new(NodeHealthSpec)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *NodeHealthStatus) DeepCopyInto(out *NodeHealthStatus) {
	*out = *in
	if in.FaultSignal != nil {
		in, out := &in.FaultSignal, &out.FaultSignal
		*out = new(FaultSignal)
		**out = **in
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 NodeHealthStatus 생성, 자동 생성 deepcopy 함수
func (in *NodeHealthStatus) DeepCopy() *NodeHealthStatus {
	if in == nil {
		return nil
	}
	out := new(NodeHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *WorkloadRun) DeepCopyInto(out *WorkloadRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// 리시버를 복사해 새 WorkloadRun 생성, 자동 생성 deepcopy 함수
func (in *WorkloadRun) DeepCopy() *WorkloadRun {
	if in == nil {
		return nil
	}
	out := new(WorkloadRun)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *WorkloadRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *WorkloadRunList) DeepCopyInto(out *WorkloadRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 WorkloadRunList 생성, 자동 생성 deepcopy 함수
func (in *WorkloadRunList) DeepCopy() *WorkloadRunList {
	if in == nil {
		return nil
	}
	out := new(WorkloadRunList)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 새 runtime.Object 생성, 자동 생성 deepcopy 함수
func (in *WorkloadRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *WorkloadRunObservation) DeepCopyInto(out *WorkloadRunObservation) {
	*out = *in
}

// 리시버를 복사해 새 WorkloadRunObservation 생성, 자동 생성 deepcopy 함수
func (in *WorkloadRunObservation) DeepCopy() *WorkloadRunObservation {
	if in == nil {
		return nil
	}
	out := new(WorkloadRunObservation)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *WorkloadRunSpec) DeepCopyInto(out *WorkloadRunSpec) {
	*out = *in
	out.Target = in.Target
}

// 리시버를 복사해 새 WorkloadRunSpec 생성, 자동 생성 deepcopy 함수
func (in *WorkloadRunSpec) DeepCopy() *WorkloadRunSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadRunSpec)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *WorkloadRunStatus) DeepCopyInto(out *WorkloadRunStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastObservedAt != nil {
		in, out := &in.LastObservedAt, &out.LastObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Observations != nil {
		in, out := &in.Observations, &out.Observations
		*out = make([]WorkloadRunObservation, len(*in))
		copy(*out, *in)
	}
	if in.RecoveredAtSeconds != nil {
		in, out := &in.RecoveredAtSeconds, &out.RecoveredAtSeconds
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// 리시버를 복사해 새 WorkloadRunStatus 생성, 자동 생성 deepcopy 함수
func (in *WorkloadRunStatus) DeepCopy() *WorkloadRunStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadRunStatus)
	in.DeepCopyInto(out)
	return out
}

// 리시버를 복사해 out에 기록하는 자동 생성 deepcopy 함수, in은 non-nil 필수
func (in *WorkloadRunTarget) DeepCopyInto(out *WorkloadRunTarget) {
	*out = *in
}

// 리시버를 복사해 새 WorkloadRunTarget 생성, 자동 생성 deepcopy 함수
func (in *WorkloadRunTarget) DeepCopy() *WorkloadRunTarget {
	if in == nil {
		return nil
	}
	out := new(WorkloadRunTarget)
	in.DeepCopyInto(out)
	return out
}
