resources:
- monitor.yaml
- gateway_podmonitor.yaml
- gateway_rules.yaml

# [PROMETHEUS-WITH-CERTS] 아래 patch는 cert-manager가 발급하고 관리하는 certificate를,
# ServiceMonitor가 안전하게 참조하도록 TLS 설정을 적용합니다.
# 함께 config/default/kustomization.yaml의 [METRICS WITH CERTS] patch도 해제하여,
# manager Deployment에 "metrics-server-cert" secret을 mount해야 합니다.
#patches:
# - path: monitor_tls_patch.yaml
#    target:
# kind: ServiceMonitor
