# 프로젝트 자체는 이 rule을 쓰지 않으며,
# cluster 관리자가 사용자 권한을 관리하도록 돕기 위해 제공한다.
#
# 해당 resource를 create/update/delete 할 수 있는 편집 권한 role이다.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-platform-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: inferencedeployment-editor-role
rules:
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - inferencedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - inferencedeployments/status
  verbs:
  - get
