# 프로젝트 자체는 이 rule을 쓰지 않으며,
# cluster 관리자가 사용자 권한을 관리하도록 돕기 위해 제공한다.
#
# 해당 resource에 대한 전체 권한('*')을 부여하는 role이다.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-platform-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: nodehealth-admin-role
rules:
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - nodehealths
  verbs:
  - '*'
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - nodehealths/status
  verbs:
  - get
