#!/usr/bin/env bash
# FR-002 — the serving pod dies and the gateway has to survive it.
#
# The load is generated by this script and the effect is read from the GATEWAY'S OWN metrics, not from the
# curl exit codes. Those are two different observers, and only the second is the one an operator would have
# in production: if the gateway's counters disagree with what the client saw, the counters are what get
# paged on, so they are what must be right.
#
# WHAT IS BEING MEASURED
#
#   error window   how long the gateway returned non-2xx after the pod was deleted
#   recovery       the moment 2xx resumes, measured from the delete
#
# Kubernetes' own endpoint propagation is inside that window and is NOT this platform's latency. Unlike
# FR-004 the two cannot be cleanly separated here — the gateway proxies to a Service, so it learns about the
# new pod exactly when kube-proxy does — and that is recorded rather than papered over.
#
# THE STEADY STATE IS A GATE
#
# Every precondition aborts. The load must be flowing and succeeding BEFORE the kill, or an error window
# afterwards is not attributable to it.
set -uo pipefail

NS=${NS:-gpu-platform-control-plane-system}
SERV=${SERV:-serving}
BACKEND=${BACKEND:-stub-llm}
GW=${GW:-localhost:8080}
PROM=${PROM:-localhost:9090}
KEY=${KEY:-premium-1}
MODEL=${MODEL:-demo-llm}
OUT=${OUT:-./ex/chaos-fr002.json}
WINDOW=${WINDOW:-120}

say () { echo "  $*"; }
die () { echo "ABORT: $*" >&2; exit 1; }
now_ns () { date +%s%N; }
ms () { echo "scale=1; $1 / 1000000" | bc; }

# -m 1, not -m 5.
#
# A failing request BLOCKS for its timeout, so the timeout is the sampling interval whenever things are
# broken — which is exactly the interval that has to be small. The first version used -m 5 and reported
# "samplingIntervalMs: 100" while collecting 3 samples across 5.3 seconds: a claimed resolution of 100ms
# against an actual one near two seconds, and a recovery figure with seconds of unstated uncertainty.
req () {
  curl -s -o /dev/null -m 1 -w '%{http_code}' -X POST "http://$GW/v1/chat/completions" \
    -H "Authorization: Bearer $KEY" -H 'Content-Type: application/json' \
    -d "{\"model\":\"$MODEL\",\"messages\":[{\"role\":\"user\",\"content\":\"hi\"}]}" 2>/dev/null
}

promq () {
  curl -sG "http://$PROM/api/v1/query" --data-urlencode "query=$1" 2>/dev/null \
    | python3 -c "
import json,sys
try: r=json.load(sys.stdin)['data']['result']
except Exception: print(''); raise SystemExit
print(r[0]['value'][1] if r else '')"
}

# ---------------------------------------------------------------- steady state
say "=== steady state ==="

kubectl -n "$NS" get deploy gateway >/dev/null 2>&1 || die "the gateway is not deployed"
[ "$(kubectl -n "$NS" get deploy gateway -o jsonpath='{.status.readyReplicas}' 2>/dev/null || echo 0)" -ge 1 ] \
  || die "the gateway has no ready replica"
[ "$(kubectl -n "$SERV" get deploy "$BACKEND" -o jsonpath='{.status.readyReplicas}' 2>/dev/null || echo 0)" -ge 1 ] \
  || die "the backend has no ready replica; there is nothing to kill"

# The gateway must be SERVING, not merely running. A 401 or 403 here would make every later non-2xx
# indistinguishable from a configuration problem that was already present.
ok=0
for _ in $(seq 5); do [ "$(req)" = "200" ] && ok=$((ok+1)); done
[ "$ok" -eq 5 ] || die "only $ok of 5 pre-fault requests succeeded; the path is already broken"
say "5/5 pre-fault requests returned 200 — the path works before the fault"

BEFORE_2XX=$(promq 'sum(gpuaas_gateway_requests_total{code="200"})')
[ -n "$BEFORE_2XX" ] || die "Prometheus has no gateway request counter; the effect could not be read from the gateway's own view"
# Counters are CUMULATIVE, and the cluster carries traffic from earlier runs and from any background load.
# The first version of this script recorded only the after value and compared that absolute against one
# run's client failures. They matched once, by coincidence, and the run was reported as proof that the
# gateway's counters miss nothing. Three repetitions showed the counter climbing 15 -> 23 -> 31 while each
# run saw nine failures: the agreement was never being tested.
BEFORE_5XX=$(promq 'sum(gpuaas_gateway_requests_total{code=~"5.."})')
BEFORE_UPSTREAM=$(promq 'sum(gpuaas_gateway_upstream_errors_total)')
say "gateway counters before — 200s: $BEFORE_2XX, 5xx: $BEFORE_5XX, upstream errors: $BEFORE_UPSTREAM"

POD=$(kubectl -n "$SERV" get pods -l app.kubernetes.io/instance="$BACKEND" -o name 2>/dev/null | head -1)
[ -n "$POD" ] || POD=$(kubectl -n "$SERV" get pods -o name 2>/dev/null | grep "$BACKEND" | head -1)
[ -n "$POD" ] || die "could not find the backend pod"
say "target: $POD"

# ---------------------------------------------------------------- inject
echo
say "=== inject: deleting the serving pod ==="
T_KILL=$(now_ns)
kubectl -n "$SERV" delete "$POD" --wait=false >/dev/null 2>&1 || die "delete failed"

# One continuous loop, sampling the client's view at ~100ms. Both edges of the error window come from the
# same series so they are ordered by construction rather than by two loops racing.
FIRST_ERR=""; LAST_ERR=""; RECOVERED=""
ERRORS=0; TOTAL=0; NOREPLY=0; CODES=""
LOOP_START=$(now_ns)
DEADLINE=$(( $(date +%s) + WINDOW ))
while [ "$(date +%s)" -lt "$DEADLINE" ]; do
  C=$(req); TOTAL=$((TOTAL+1))
  CODES="$CODES$C "
  # curl reports 000 when it never got an HTTP response at all — a connection refused or its own timeout.
  # The gateway cannot count a request that did not reach it, so these are excluded from the comparison
  # rather than held against its counters.
  [ "$C" = "000" ] && NOREPLY=$((NOREPLY+1))
  if [ "$C" = "200" ]; then
    # Recovery counts only after an error was actually seen; otherwise a kill that never disrupted anything
    # would report an instant recovery and look like a success.
    [ -n "$FIRST_ERR" ] && { RECOVERED=$(now_ns); break; }
  else
    ERRORS=$((ERRORS+1))
    [ -z "$FIRST_ERR" ] && FIRST_ERR=$(now_ns)
    LAST_ERR=$(now_ns)
  fi
  sleep 0.1
done

# The MEASURED interval, not the nominal one. Every latency below is bounded by it, because the transition
# it dates could have happened at any point since the previous sample.
RESOLUTION_NS=$(( ($(now_ns) - LOOP_START) / TOTAL ))
say "effective sampling interval: $(ms $RESOLUTION_NS)ms over $TOTAL samples"

if [ -z "$FIRST_ERR" ]; then
  say "no request ever failed — either the delete was absorbed by a second replica or the sampling missed the gap"
  DISRUPTED=false
else
  DISRUPTED=true
  say "first error $(ms $(( FIRST_ERR - T_KILL )))ms after the delete"
  if [ -n "$RECOVERED" ]; then
    say "recovered $(ms $(( RECOVERED - T_KILL )))ms after the delete ($(ms $(( RECOVERED - FIRST_ERR )))ms of errors), +/- one $(ms $RESOLUTION_NS)ms sample"
  else
    say "NEVER recovered within ${WINDOW}s"
  fi
fi
say "$ERRORS of $TOTAL sampled requests failed"
say "codes: $(echo "$CODES" | tr ' ' '\n' | sort | uniq -c | tr '\n' ' ')"

# ---------------------------------------------------------------- the gateway's own view
echo
say "=== the gateway's own counters ==="
sleep 20   # let at least one scrape land after recovery
AFTER_5XX=$(promq 'sum(gpuaas_gateway_requests_total{code=~"5.."})')
AFTER_UPSTREAM=$(promq 'sum(gpuaas_gateway_upstream_errors_total)')
AFTER_FALLBACK=$(promq 'sum(gpuaas_gateway_backend_fallbacks_total)')
D_5XX=$(echo "${AFTER_5XX:-0} - ${BEFORE_5XX:-0}" | bc)
D_UPSTREAM=$(echo "${AFTER_UPSTREAM:-0} - ${BEFORE_UPSTREAM:-0}" | bc)
ANSWERED=$(( ERRORS - NOREPLY ))
say "requests_total{5xx}   delta $D_5XX   (${BEFORE_5XX:-0} -> ${AFTER_5XX:-0})"
say "upstream_errors_total delta $D_UPSTREAM   (${BEFORE_UPSTREAM:-0} -> ${AFTER_UPSTREAM:-0})"
say "backend_fallbacks_total        ${AFTER_FALLBACK:-0}"
say "client failures $ERRORS, of which $NOREPLY never got a reply — $ANSWERED are the gateway's to account for"

# The client saw failures and the gateway's counters must agree. A gateway whose metrics stay clean through
# an outage its clients felt is a worse problem than the outage, because it is the version an on-call
# engineer would be looking at.
# The comparison is DELTA against the failures the gateway actually answered. Counting the client's own
# timeouts against it would demand the impossible; ignoring the before value would compare a cumulative
# total against one run's count, which is what the first version did.
AGREES=unknown
if [ "$DISRUPTED" = true ]; then
  if [ "$(echo "$D_5XX >= $ANSWERED" | bc)" = "1" ] && [ "$ANSWERED" -gt 0 ]; then AGREES=true; else AGREES=false; fi
fi
[ "$AGREES" = false ] && say "WARNING: the gateway's counters do not account for the failures it answered"

# ---------------------------------------------------------------- record
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
{
  "experiment": "FR-002 serving pod killed",
  "backend": "$SERV/$BACKEND",
  "injection": "kubectl delete pod",
  "steadyStateEstablished": true,
  "samplingIntervalMs": $(ms $RESOLUTION_NS),
  "samplingNote": "measured, not nominal: a failing request blocks for its timeout, so the interval widens exactly when the measurement matters. Every latency below carries one interval of uncertainty.",
  "disrupted": $DISRUPTED,
  "latenciesMs": {
    "killToFirstError": $( [ -n "$FIRST_ERR" ] && ms $(( FIRST_ERR - T_KILL )) || echo null ),
    "killToRecovery": $( [ -n "$RECOVERED" ] && ms $(( RECOVERED - T_KILL )) || echo null ),
    "errorWindow": $( [ -n "$FIRST_ERR" ] && [ -n "$RECOVERED" ] && ms $(( RECOVERED - FIRST_ERR )) || echo null )
  },
  "clientView": {
    "sampled": $TOTAL,
    "failed": $ERRORS,
    "neverAnswered": $NOREPLY,
    "answeredByGateway": $ANSWERED,
    "note": "a 000 is curl never receiving an HTTP response; the gateway cannot count a request that did not reach it"
  },
  "gatewayView": {
    "requests5xxDelta": $D_5XX,
    "upstreamErrorsDelta": $D_UPSTREAM,
    "requests5xxCumulative": ${AFTER_5XX:-0},
    "backendFallbacks": ${AFTER_FALLBACK:-0},
    "agreesWithClient": "$AGREES"
  },
  "attribution": "the error window contains Kubernetes endpoint propagation, which this platform does not control and which cannot be separated here because the gateway proxies to a Service"
}
EOF
echo
say "record written to $OUT"
[ "$DISRUPTED" = true ] && [ -n "$RECOVERED" ] && [ "$AGREES" = true ]
