# 프로젝트 sample CR manifest 목록입니다.
resources:
- platform_v1_nodehealth.yaml
- platform_v1_gpuquotapolicy.yaml
- platform_v1_inferencedeployment.yaml
- platform_v1_mltrainingjob.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
