apiVersion: platform.lkhun9311.github.io/v1
kind: GPUQuotaPolicy
metadata:
  labels:
    app.kubernetes.io/name: gpu-platform-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: team-vision-quota
spec:
  tenant: team-vision
  targetNamespace: team-vision
  gpuClass: l40s
  limits:
    gpuCount: 8
