apiVersion: platform.lkhun9311.github.io/v1
kind: NodeHealth
metadata:
  labels:
    app.kubernetes.io/name: gpu-platform-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: platform-worker
spec:
  nodeName: platform-worker
  gpuClass: l40s
