apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - root.yaml
  - crds.yaml
  - operator.yaml
  - gateway.yaml
  - observability.yaml
  - device-plugin.yaml
  - samples.yaml
