# 이 파일은 kustomize가 CRD의 name과 namespace 참조를 어떻게 치환할지 알려준다.
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: CustomResourceDefinition
    version: v1
    group: apiextensions.k8s.io
    path: spec/conversion/webhook/clientConfig/service/name

varReference:
- path: metadata/annotations
