# 이 kustomization.yaml은 단독으로 실행하도록 만든 것이 아니다,
# 이 kustomize package 밖에 있는 service 이름과 namespace에 의존하므로,
# config/default를 통해 실행해야 한다.
resources:
- bases/platform.lkhun9311.github.io_nodehealths.yaml
- bases/platform.lkhun9311.github.io_workloadruns.yaml
- bases/platform.lkhun9311.github.io_gpuquotapolicies.yaml
- bases/platform.lkhun9311.github.io_inferencedeployments.yaml
- bases/platform.lkhun9311.github.io_mltrainingjobs.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] webhook을 활성화하려면 [WEBHOOK] prefix가 붙은 모든 섹션을 주석 해제한다,
# 아래 patch는 각 CRD의 conversion webhook을 활성화한다.
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] webhook을 활성화하려면 아래 섹션을 주석 해제한다,
# 아래 설정은 kustomize가 CRD를 어떻게 kustomization할지 알려준다.
#configurations:
# - kustomizeconfig.yaml
